// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AnyStatus.VSPackage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolWindowPackageString = "b8682407-a118-4468-9c71-d1f7c6a312ec";
        public const string guidToolWindowPackageCmdSetString = "c420854f-cac2-4492-8067-ecf632228390";
        public static Guid guidToolWindowPackage = new Guid(guidToolWindowPackageString);
        public static Guid guidToolWindowPackageCmdSet = new Guid(guidToolWindowPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowCommandId = 0x0100;
        public const int ToolbarId = 0x1000;
        public const int ToolbarGroup1Id = 0x1001;
        public const int ToolbarGroup2Id = 0x1005;
        public const int ToolbarGroup3Id = 0x1006;
        public const int ToolbarGroup4Id = 0x1011;
        public const int optionsToolbarCommandId = 0x1002;
        public const int refreshToolbarCommandId = 0x1003;
        public const int helpToolbarCommandId = 0x1004;
        public const int collapseToolbarCommandId = 0x1007;
        public const int expandToolbarCommandId = 0x1008;
        public const int newItemToolbarCommandId = 0x1009;
        public const int addFolderToolbarCommandId = 0x1010;
    }
}
