version: 1.0.{build}

skip_commits:
  files:
    - art/*
    - '**/*.md'
  
branches:
  only:
  - master

configuration: Release

platform: Any CPU

image: Visual Studio 2017 RC

environment:
    COVERALLS_REPO_TOKEN:
        secure: jlcm0lBlKUqgOgzGEtwALYs3UT1LcHOJ8gTw4/Z+BrHnXharzwEh1FM+fDYEQ715
    
install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - cmd: nuget restore src\AnyStatus.sln

build_script:
  - msbuild src\AnyStatus.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test:
 assemblies:
  - AnyStatus.Tests.dll

after_test:
 - cmd: src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[AnyStatus*]* -[AnyStatus.Tests]* -[AnyStatus.Integration.Tests]* -[FluentScheduler]*" -target:"vstest.console" -targetargs:"/testcontainer:src/AnyStatus.Tests/bin/Release/AnyStatus.Tests.dll /testcontainer:src/AnyStatus.Integration.Tests/bin/Release/AnyStatus.Integration.Tests.dll" -output:coverage.xml
 - cmd: src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
 - ps: Vsix-PushArtifacts | Vsix-PublishToGallery

artifacts:
 - path: src\AnyStatus.VSPackage\bin\Release\AnyStatus.vsix

# test_script:
# - vstest.console /logger:Appveyor ".\src\AnyStatus.Tests\bin\Release\AnyStatus.Tests.dll"